backend:
  name: git-gateway
  branch: main
media_folder: assets/uploads
collections:
  - name: "recipe" # Used in routes, e.g., /admin/collections/blog
    label: "Recipe" # Used in the UI
    folder: "collections/recipes" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "blog"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Ingredients"
        name: "ingredients"
        widget: "list"
        default: []
